### ISSUE TITLE
make available in fdroid app-store

### ISSUE THREAD

**Issue by k3b** [angelgladin/Photo_EXIF_Toolkit#16]
Is it possible to make the app available in http://f-droid.org/ appstore? if you need support with f-droid release i can help you

**Comment by k3b** [comment]
i just saw that the app uses google-maps-api (com.google.android.gms:play-services) which is not fos so the app cannot go into http://f-droid.org/ appstore :-(

**Comment by angelgladin** [comment]
I didn't know that, that's a shame ;(

**Comment by k3b** [comment]
f-droid does not allow non-free components (google-play-services, google-maps)


Is there a binary version of Photo_Exif_Toolkit available?

compiling the app with "gradlew installDebug" fails with 

Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.
DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

i am using java  1.8.0_102-b14 64 bit on windows-7/64-bit

**Comment by angelgladin** [comment]
I see... You can fix it enabling the Multidex (check this [link](https://developer.android.com/studio/build/multidex.html)).

**Comment by angelgladin** [comment]
And about the binary, I'll upload the apk as soon as possible, I forgot to do it. But if you add the Multidex it should work, if doesn't, don't hesitate in contact me.

**Comment by k3b** [comment]
yes with Multidex  it compiles but the app crashes on my android-4.2 (api-17)  because of 
<pre>
FATAL EXCEPTION: main
	java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/com.angelgladin.photoexiftoolkit-1.apk
		at android.app.ActivityThread.installProvider(ActivityThread.java:4822)
		at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
		at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:137)
		at android.app.ActivityThread.main(ActivityThread.java:5041)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:511)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
		at dalvik.system.NativeStart.main(Native Method)
	 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/com.angelgladin.photoexiftoolkit-1.apk
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
		at android.app.ActivityThread.installProvider(ActivityThread.java:4807)
		at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432) 
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372) 
		at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
		at android.os.Handler.dispatchMessage(Handler.java:99) 
		at android.os.Looper.loop(Looper.java:137) 
		at android.app.ActivityThread.main(ActivityThread.java:5041) 
		at java.lang.reflect.Method.invokeNative(Native Method) 
		at java.lang.reflect.Method.invoke(Method.java:511) 
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584) 
		at dalvik.system.NativeStart.main(Native Method) 
</pre>

you should also remove the ".idea" folder and  from github and the google_maps_api.xml files.

google_maps_api.xml contains you google-key. it is in the .gitignore but the file is still in the repository

now i have to go to bed. it is 03 hours in the morning and tomorrow i have to work ....

**Comment by angelgladin** [comment]
That's kind of weird, I even didn't use Firebase (?).
Thanks for the advices. I'll feel very thankful if you open an issue(s) with the problem(s) and explaining it/them, or if want you can fix it/them and then create a pull request.

**Comment by IzzySoft** [comment]
For those who wanted to have it in F-Droid: I have added it to my F-Droid compatible repo a few weeks ago, see [here](https://apt.izzysoft.de/fdroid/index/apk/com.angelgladin.photoexiftoolkit). The repo's [main page](https://apt.izzysoft.de/fdroid/) on its top explains in short how you can use it with your F-Droid client. So whenever @angelgladin releases a new version (with correctly increased versinName **and** versionCode :smile_cat: ), that update should automatically appear in the repo within ~24h.

**Comment by angelgladin** [comment]
@k3b Hey, I've recently fixed all the problems when compiling and running the app, it'll be great if you try it out!
